Repository GSG-CF05/Novelty-Travel-Team5, pull requests merged in 2022-03, with the labels that each got.

#4 Create readme file
  README.md
Labels: t4h, done

#18 create the home page design using html and css
  assets/images/home-page/barcelona.svg
  assets/images/home-page/hotel1.svg
  assets/images/home-page/hotel2.svg
  assets/images/home-page/rome.svg
  home-page/home.html
  home-page/styles/home.css
  styles/global.css
Labels: approved

#20 Add desktop version of landing page relates #19
  assets/images/landing-page/bg.png
  index.html
  styles/global.css
  styles/landing.css
Labels: approved

#27 add the holidays page design using html and css
  assets/images/holidays-page/christmas.svg
  assets/images/holidays-page/filter.svg
  assets/images/holidays-page/holiday.jpg
  assets/images/holidays-page/independence.svg
  assets/images/holidays-page/labour.svg
  assets/images/holidays-page/lutherKing.svg
  assets/images/holidays-page/newYear.svg
  assets/images/holidays-page/thanksgiving.svg
  holidays-page/holidays.html
  holidays-page/styles/holidays.css
Labels: approved

#29 add js code for the two main functionalities in the page
  home-page/home.html
  home-page/js/home.js
  home-page/styles/home.css
Labels: approved

#15 7 overview destenation page
  overview/destenation-page/destenation.html
  overview/destenation-page/img/favicon.png
  overview/destenation-page/img/icons.svg
  overview/destenation-page/img/logo-green-round.png
  overview/destenation-page/img/logo-green-small.png
  overview/destenation-page/img/logo-green.png
  overview/destenation-page/img/logo-white.png
  overview/destenation-page/img/pin.png
  overview/destenation-page/img/tours/tour-1-cover.jpg
  overview/destenation-page/img/tours/tour-4-1.jpg
  overview/destenation-page/style.css
Labels: t4h, approved

#31 add js code that is responsible for fetching and placing holidays on page.
  holidays-page/js/holidays.js
Labels: approved

#38 store country name in local storage
  home-page/js/home.js
Labels: awaiting review

#36 add responsive css styling rules
  assets/images/holidays-page/background.svg
  holidays-page/styles/holidays.css
  holidays-page/styles/media.css
Labels: approved

#41 update readme file
  README.md
Labels: awaiting review

#17 16 destination page
  destination-page/destination.html
  destination-page/js/destination.js
  destination-page/styles/destination.css
Labels: T1h, awaiting review

#47 add live link
  README.md
Labels: approved

#45 add js to locations age relates #25
  holidays-page/js/data.json
  locations-page/js/locations.js
  locations-page/locations.html
Labels: approved

#49 responsive destination relates #48
  destination-page/styles/media.css
Labels: approved
